### ISSUE TITLE
Typos in Wireshark.md

### ISSUE THREAD

**Issue by de-azra** [strandjs/IntroLabs#11]
file:///C:/Users/adhd/IntroLabs/IntroClassFiles/index.html#!Tools/IntroClass/Wireshark/Wireshark.md

tcpdump, **lets** take

-> let's

having some **visulizations** is very

-> visualizations

Wireshark. **Basicly**, it is key

-> Basically

**Lets** get started.

-> Let's

The second **windows** shows a

-> window

If it is.... You must

-> you

highlights the **corasponding**

-> corresponding

This means **wirreshark** can decode

-> wireshark

fly and **automaticly** highlight

-> automatically

the **relevent** data

-> relevant

Ok, now, **lets** play with some statistics.

-> let's

Please select **Staticstics** >

-> Statistics

If you **looks** closely, there is a lot

-> look

Now, **lets** look at **Statisctics** >

-> let's
-> Statistics

This gives us a breakdown of who was chatting with what **systems** the most.

-> system

the **opisite** direction

-> opposite

Now, lets play with some basic

-> let's

with possible **compleation** options

-> completion

quickly drill in on any **spcific** **protocls** you

-> specific
-> protocols

for that **spcific** string:

-> specific

**Comment by strandjs** [comment]
Fixed.

Thanks!
