### ISSUE TITLE
Typo in Menu Button

### ISSUE THREAD

**Issue by de-azra** [strandjs/IntroLabs#12]
file:///C:/Users/adhd/IntroLabs/IntroClassFiles/index.html#!index.md

-> Cyber Deception

say "Comming Soon!!!"

should be "Coming soon!"
![soon](https://user-images.githubusercontent.com/67689160/102524811-c5583b80-4099-11eb-813b-3ba02bf8bf72.PNG)

**Comment by strandjs** [comment]
Fixed.  Thanks!
