### ISSUE TITLE
Typos in DomainLogReview

### ISSUE THREAD

**Issue by Sharkinator113** [strandjs/IntroLabs#14]
file:///C:/IntroLabs/IntroClassFiles/index.html#!Tools/IntroClass/DomainLogReview/DomainLogReview.md

Now, please click on the header column called Event ID. This will sort the logs by ID number we are doing this because we want to quickly get to the event IDs of **4476:**

should be event 4776

**Comment by strandjs** [comment]
Fixed.

Thanks!
