### ISSUE TITLE
Typos in DomainLogReview.md

### ISSUE THREAD

**Issue by de-azra** [strandjs/IntroLabs#17]
file:///C:/Users/adhd/IntroLabs/IntroClassFiles/index.html#!Tools/IntroClass/DomainLogReview/DomainLogReview.md

We will start by using DeepBlueCLI, then **moving** into looking directly at the event logs themselves.

-> move

We have 240 logon failures. That... **Is** a lot for this small org.

-> is

event IDs of **4476**:

-> 4776

**Comment by strandjs** [comment]
Fixed.  Thanks!
