### ISSUE TITLE
Labs not ordered in Intro to SOC class web dropdown

### ISSUE THREAD

**Issue by dev-id** [strandjs/IntroLabs#21]
The dropdown for the Intro to SOC class lists each of the labs, but the order does not match the sequence they are used in the class.

![image](https://user-images.githubusercontent.com/3866018/106794896-093dda80-661f-11eb-9231-12cf30699b48.png)

(class is still ongoing for me, but so far we've done, in order, Windows CLI, DeepBlueCLI, Linux CLI, TCPDump, Wireshark)

**Comment by strandjs** [comment]
I will be changing this up in the future.  Thanks!
