### ISSUE TITLE
Typos in LinuxCLI.md

### ISSUE THREAD

**Issue by de-azra** [strandjs/IntroLabs#6]
file:///C:/Users/adhd/IntroLabs/IntroClassFiles/index.html#!Tools/IntroClass/LinuxCLI/LinuxCLI.md

The **fist** will be where we run the backdoor.

-> first

On your **Linux** terminal

-> you switch between capitalizing Linux (as in Linux terminal here, Linux backdoor later) and lowercase (linux system later)

We will next need to create a fifo backpipe:
/#mknod backpipe p

-> Repetition

Next, **lets** start the backdoor:

-> let's

back into the netcat **listiner**.

-> listener

Basicly, this will create a backdoor **listnening**

-> listening

Now, **lets** connect:

-> let's

Now, **lets** type some

-> let's

Also notice there was **not** message saying

-> no

It just drops our curser back to the left side of the screen.

-> cursor

Now, **lets** open

-> let's

We want to be root **becasue** **doing** looking at network

->"because"
-> remove the doing

**Basicly**, it is very **had** to do your job as a SOC

-> Basically
-> hard

Lets start by

-> Let's

ports that are being **used.just**

-> used. Just

Now lets

-> let's

Lets look at the full processes

-> Let's

This is a for all processes. **U** for sorted by user and x to **indlude** the processes using a teletype terminal.

-> I know it's cause it's the start of the sentence, but a capital U is actually a different switch
-> include

It allows us to see data associated with the various **proccess** directly.

-> processes

This is very, very **usefull** as

-> useful

**what, exacly** a program is doing.

-> remove the comma

**Comment by strandjs** [comment]
Fixed.

Thanks!
