### ISSUE TITLE
Typos in TCPDump.md

### ISSUE THREAD

**Issue by de-azra** [strandjs/IntroLabs#8]
file:///C:/Users/adhd/IntroLabs/IntroClassFiles/index.html#!Tools/IntroClass/TCPDump/TCPDump.md

and security **analyest**

-> analyst

Well, it is showing each **packets** **Timestamp**:

-> packet's
-> timestamp

can create filters for **litteraly** every

-> literally

**Lets** add port number.

-> Let's

either sent or **recived** **to** port

-> received
-> by

**Lets** dig into the packet

-> Let's

We can also see the raw Hex, if that is your sort of **thing with** the -X flag:

-> thing, with

This is very usefull when

-> useful

Here is a great **resoruce** to try

-> resource

**Comment by strandjs** [comment]
Fixed.

Thanks!
